[tool.poetry]
name = "rs-website2"
version = "0.1.0"
description = ""
authors = ["JeroenLam <git@jeroenlam.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aider-install = "^0.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
